import portfolioImage1 from "@/assets/img/gallery/1.jpg";
import portfolioImage2 from "@/assets/img/gallery/2.jpg";
import portfolioImage3 from "@/assets/img/gallery/3.jpg";
import portfolioImage4 from "@/assets/img/gallery/4.jpg";
import portfolioImage5 from "@/assets/img/gallery/5.jpg";
import portfolioImage6 from "@/assets/img/gallery/6.jpg";
import portfolioImage7 from "@/assets/img/gallery/7.jpg";
import portfolioImage8 from "@/assets/img/gallery/8.jpg";
import portfolioImage9 from "@/assets/img/gallery/9.jpg";
import portfolioImage10 from "@/assets/img/gallery/10.jpg";
import portfolioImage11 from "@/assets/img/img-slide/11.jpg";
import portfolioImage12 from "@/assets/img/img-slide/12.jpg";
import portfolioImage13 from "@/assets/img/img-slide/13.jpg";
import portfolioImage14 from "@/assets/img/img-slide/21.jpg";
import portfolioImage15 from "@/assets/img/img-slide/22.jpg";
import portfolioImage16 from "@/assets/img/img-slide/23.jpg";
import portfolioImage17 from "@/assets/img/img-slide/24.jpg";
import portfolioImage18 from "@/assets/img/img-slide/1.jpg";
import portfolioImage19 from "@/assets/img/img-slide/2.jpg";
import portfolioImage20 from "@/assets/img/img-slide/3.jpg";
import portfolioImage21 from "@/assets/img/img-slide/4.jpg";
import portfolioImageLarge1 from "@/assets/img/service/19.jpg";
import portfolioImageLarge2 from "@/assets/img/service/21.jpg";
import portfolioImageLarge3 from "@/assets/img/service/22.jpg";
import portfolioImageLarge4 from "@/assets/img/service/23.jpg";

const getAllPortfolios = () => {
  const portfolios = [
    {
      id: 1,
      title: "Portfolio Link",
      path: portfolioImage1.src,
      desc: "Web Design & Development, Branding",
      icon: <i className="fas fa-search"></i>,
      img: portfolioImage1,
      imgLarge: portfolioImageLarge1,
      dep: "Marketing Agency",
      duration: "1500",
    },
    {
      id: 2,
      title: "Inline Description",
      path: "#ltn__inline_description_1",
      desc: "Web Design & Development, Branding",
      icon: <i className="far fa-file-alt"></i>,
      img: portfolioImage2,
      imgLarge: portfolioImageLarge3,
      dep: "Marketing Agency",
      duration: "1700",
    },
    {
      id: 3,
      title: "Youtube Video",
      path: "https://www.youtube.com/embed/6v2L2UGZJAM?version=3",
      desc: "Web Design & Development, Branding",
      icon: <i className="fab fa-youtube"></i>,
      img: portfolioImage3,
      imgLarge: portfolioImageLarge4,
      dep: "Marketing Agency",
      duration: "1900",
    },
    {
      id: 4,
      title: "Vimeo Video",
      path: "https://player.vimeo.com/video/47362400",
      desc: "Web Design & Development, Branding",
      icon: <i className="fab fa-vimeo-v"></i>,
      img: portfolioImage4,
      imgLarge: portfolioImageLarge1,
      dep: "Marketing Agency",
      duration: "2100",
    },
    {
      id: 5,
      title: "HTML5 Video",
      path: "/media/1.mp4",
      desc: "Web Design & Development, Branding",
      icon: <i className="fas fa-video"></i>,
      img: portfolioImage5,
      imgLarge: portfolioImageLarge2,
      dep: "Marketing Agency",
      duration: "2300",
    },
    {
      id: 6,
      title: "Google Map",
      path: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1575.9076122223137!2d144.96590401578402!3d-37.81779982944919!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x6ad642b6af832249%3A0xe39e415e49a7c44e!2sFlinders%20Street%20Railway%20Station!5e0!3m2!1sen!2sbd!4v1598113544515!5m2!1sen!2sbd",
      desc: "Web Design & Development, Branding",
      icon: <i className="fas fa-map-marker-alt"></i>,
      img: portfolioImage6,
      imgLarge: portfolioImageLarge3,
      dep: "Marketing Agency",
      duration: "2500",
    },
    {
      id: 7,
      title: "Image Caption",
      path: portfolioImage7.src,
      desc: "Web Design & Development, Branding",
      icon: <i className="fab fa-acquisitions-incorporated"></i>,
      img: portfolioImage7,
      imgLarge: portfolioImageLarge4,
      dep: "Marketing Agency",
      duration: "2700",
    },
    {
      id: 8,
      title: "Not Found",
      path: "img/gallery/no-image.jpg",
      desc: "Web Design & Development, Branding",
      icon: <i className="fas fa-not-equal"></i>,
      img: portfolioImage8,
      imgLarge: portfolioImageLarge1,
      dep: "Marketing Agency",
      duration: "2900",
    },

    {
      id: 9,
      title: "Portfolio Link",
      path: portfolioImage9.src,
      desc: "Web Design & Development, Branding",
      icon: <i className="fas fa-search"></i>,
      img: portfolioImage9,
      imgLarge: portfolioImageLarge2,
      dep: "Marketing Agency",
      duration: "1500",
    },
    {
      id: 10,
      title: "Portfolio Link",
      path: portfolioImage10.src,
      desc: "Web Design & Development, Branding",
      icon: <i className="fas fa-search"></i>,
      img: portfolioImage10,
      imgLarge: portfolioImageLarge3,
      dep: "Marketing Agency",
      duration: "1500",
    },
    {
      id: 11,
      title: "Portfolio Link",
      path: portfolioImage1.src,
      desc: "Web Design & Development, Branding",
      icon: <i className="fas fa-search"></i>,
      img: portfolioImage1,
      imgLarge: portfolioImageLarge4,
      dep: "Marketing Agency",
      duration: "1500",
    },
    {
      id: 12,
      title: "Portfolio Link",
      path: portfolioImage2.src,
      desc: "Web Design & Development, Branding",
      icon: <i className="fas fa-search"></i>,
      img: portfolioImage2,
      imgLarge: portfolioImageLarge1,
      dep: "Marketing Agency",
      duration: "1500",
    },
    {
      id: 13,
      title: "Hilix Nova Car Solutions.",
      path: "",
      desc: "trouble shooting",
      icon: <i className="fas fa-not-equal"></i>,
      img: portfolioImage11,
      imgLarge: portfolioImageLarge2,
      dep: "trouble shooting",
      duration: "2900",
    },

    {
      id: 14,
      title: "Hilix Nova Car Solutions.",
      path: "",
      desc: "Web Design & Development, Branding",
      icon: <i className="fas fa-search"></i>,
      img: portfolioImage12,
      imgLarge: portfolioImageLarge3,
      dep: "trouble shooting",
      duration: "1500",
    },
    {
      id: 15,
      title: "Hilix Nova Car Solutions.",
      path: "",
      desc: "Web Design & Development, Branding",
      icon: <i className="fas fa-search"></i>,
      img: portfolioImage13,
      imgLarge: portfolioImageLarge4,
      dep: "trouble shooting",
      duration: "1500",
    },
    {
      id: 16,
      title: "Hilix Nova Car Solutions.",
      path: "",
      desc: "Web Design & Development, Branding",
      icon: <i className="fas fa-search"></i>,
      img: portfolioImage11,
      imgLarge: portfolioImageLarge1,
      dep: "trouble shooting",
      duration: "1500",
    },
    {
      id: 17,
      title: "Hilix Nova Car Solutions.",
      path: "",
      desc: "Web Design & Development, Branding",
      icon: <i className="fas fa-search"></i>,
      img: portfolioImage13,
      imgLarge: portfolioImageLarge2,
      dep: "trouble shooting",
      duration: "1500",
    },
    {
      id: 18,
      title: "BMW Pro Street Car",
      path: "",
      desc: "trouble shooting",
      icon: <i className="fas fa-not-equal"></i>,
      img: portfolioImage15,
      imgLarge: portfolioImageLarge3,
      dep: "Sports Car",
      duration: "2900",
    },

    {
      id: 19,
      title: "BMW Pro Street Car",
      path: "",
      desc: "Web Design & Development, Branding",
      icon: <i className="fas fa-search"></i>,
      img: portfolioImage14,
      imgLarge: portfolioImageLarge4,
      dep: "Sports Car",
      duration: "1500",
    },
    {
      id: 20,
      title: "BMW Pro Street Car",
      path: "",
      desc: "Web Design & Development, Branding",
      icon: <i className="fas fa-search"></i>,
      img: portfolioImage15,
      imgLarge: portfolioImageLarge1,
      dep: "Sports Car",
      duration: "1500",
    },
    {
      id: 21,
      title: "BMW Pro Street Car",
      path: "",
      desc: "Web Design & Development, Branding",
      icon: <i className="fas fa-search"></i>,
      img: portfolioImage16,
      imgLarge: portfolioImageLarge2,
      dep: "Sports Car",
      duration: "1500",
    },
    {
      id: 22,
      title: "BMW Pro Street Car",
      path: "",
      desc: "Web Design & Development, Branding",
      icon: <i className="fas fa-search"></i>,
      img: portfolioImage17,
      imgLarge: portfolioImageLarge3,
      dep: "Sports Car",
      duration: "1500",
    },
    {
      id: 23,
      title: "BMW Pro Street Car",
      path: "",
      desc: "Web Design & Development, Branding",
      icon: <i className="fas fa-search"></i>,
      img: portfolioImage19,
      imgLarge: portfolioImageLarge4,
      dep: "Sports Car",
      duration: "1500",
    },
    {
      id: 24,
      title: "BMW Pro Street Car",
      path: "",
      desc: "Web Design & Development, Branding",
      icon: <i className="fas fa-search"></i>,
      img: portfolioImage20,
      imgLarge: portfolioImageLarge1,
      dep: "Sports Car",
      duration: "1500",
    },
    {
      id: 25,
      title: "BMW Pro Street Car",
      path: "",
      desc: "Web Design & Development, Branding",
      icon: <i className="fas fa-search"></i>,
      img: portfolioImage21,
      imgLarge: portfolioImageLarge2,
      dep: "Sports Car",
      duration: "1500",
    },
    {
      id: 26,
      title: "BMW Pro Street Car",
      path: "",
      desc: "Web Design & Development, Branding",
      icon: <i className="fas fa-search"></i>,
      img: portfolioImage11,
      imgLarge: portfolioImageLarge3,
      dep: "Sports Car",
      duration: "1500",
    },
    {
      id: 27,
      title: "BMW Pro Street Car",
      path: "",
      desc: "Web Design & Development, Branding",
      icon: <i className="fas fa-search"></i>,
      img: portfolioImage12,
      imgLarge: portfolioImageLarge4,
      dep: "Sports Car",
      duration: "1500",
    },
    {
      id: 28,
      title: "BMW Pro Street Car",
      path: "",
      desc: "Web Design & Development, Branding",
      icon: <i className="fas fa-search"></i>,
      img: portfolioImage18,
      imgLarge: portfolioImageLarge1,
      dep: "Sports Car",
      duration: "1500",
    },
  ];
  return portfolios;
};

export default getAllPortfolios;
